### ISSUE TITLE
Old doc of each sub projects

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_docs#22]
Seeing http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/index.html, it is not latest because it has no **Tutorials** section.
https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/doc/tutorials

<img src="https://cloud.githubusercontent.com/assets/4310419/25311150/70637b16-2834-11e7-92ee-9dc5611dd437.png" width="80%" />

**Comment by wkentaro** [comment]
@k-okada could you please add me the admin of read the docs?

http://readthedocs.org/projects/jsk-docs/versions/

**Comment by k-okada** [comment]
done

--
◉ Kei Okada


2017-04-23 14:55 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Ah, I mean project in readthedocs http://readthedocs.org/projects/jsk-docs/

**Comment by wkentaro** [comment]
I can't access the settings section:

![image](https://cloud.githubusercontent.com/assets/4310419/25312520/7e81af34-2856-11e7-89df-1f2becbc22c4.png)

**Comment by k-okada** [comment]
done

--
◉ Kei Okada


2017-04-23 18:56 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Thank you.
I wiped the latest version and re-built it.
Now there is the Tutorials.
